name: Build/release
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.ELECTRON_BUILDER }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Export artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaryFiles
          path: dist/Computer Tester For Trailhead Academy Events Setup 1.0.0.exe
