name: Build/release
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # - name: Install Node.js, NPM and Yarn
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 18.x

      # - name: Build/release Electron app
      #   uses: samuelmeuli/action-electron-builder@v1
      #   with:
      #     github_token: ${{ secrets.ELECTRON_BUILDER }}
      #     release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      # - name: Export artifacts
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   with:
      #     files: |
      #       dist/*.exe

      - name: Build
        run: echo "Hello World" > dist/Release 0.0.0.txt
      - name: Test
        run: cat dist/Release 0.0.0.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/Rel*.txt
