name: Build/release
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.ELECTRON_BUILDER }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      # - name: Export artifacts
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   with:
      #     files: |
      #       dist/*.exe

      # # Must use Windows paths!
      # - name: Build
      #   run: |
      #     mkdir dist
      #     echo "Hello World" > "dist\Release 0.0.0.txt"
      # - name: Test
      #   run: more "dist\Release 0.0.0.txt"
      # - name: Release
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: |
      #     copy ".\dist\Rel*.txt" ".\bin"
      #     git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
      #     git config --global user.email "andresperezf@yahoo.com"
      #     git status
      #     git add .
      #     git status
      #     git commit -m "Built"
      #     git status
